###
GET http://localhost:8080/api/global

###
GET http://localhost:8080/api/global/1


###
POST http://localhost:8080/api/global
Content-Type: application/json

{
    "name": "Jonathan",
    "email": "jaromerot@gmail.com"
}